# Summoner
# {
#     "profileIconId": 29,
#     "name": "dive top only",
#     "puuid": "K8UywUhKjlhrn7ohI0aWGNXHF8q9MlaxjesvctTq9Wu4awCqoP2OXqBrv8-6KlTRpPxzixLGPxxdgA",
#     "summonerLevel": 43,
#     "accountId": "NqVM9Re0L6bwYdjiKgjFijBSq3OKANSb_8T1-R2wjzX7TPQTmzbwH31A",
#     "id": "To4Oab79ZEY_ay-hFNbxgSPdnrDGI4iKAEI62AWYKPpoL8UH",
#     "revisionDate": 1583820336000
# }

# MatchList
# "matches": [
#     {
#         "lane": "TOP",
#         "gameId": 3322020941,
#         "champion": 39,
#         "platformId": "NA1",
#         "timestamp": 1583995753532,
#         "queue": 420,
#         "role": "SOLO",
#         "season": 13
#     },

# Match
# {
#     "seasonId": 13,
#     "queueId": 420,
#     "gameId": 3322020941,
#     "participantIdentities": [
#         {
#             "player": {
#                 "currentPlatformId": "NA1",
#                 "summonerName": "Aspect02",
#                 "matchHistoryUri": "/v1/stats/player_history/NA1/246666621",
#                 "platformId": "NA1",
#                 "currentAccountId": "20DiqhRnAsTq8vZUFG-2VY8m2-2j4harJ3etrWnv4-pWt1k",
#                 "profileIcon": 3464,
#                 "summonerId": "Y_IB7mVxhDsP9jEn9mi96nP3bm8PyHlsTgkjWwJtALVUqeo",
#                 "accountId": "20DiqhRnAsTq8vZUFG-2VY8m2-2j4harJ3etrWnv4-pWt1k"
#             },
#             "participantId": 1
#         },
#         {
#             "player": {
#                 "currentPlatformId": "NA1",
#                 "summonerName": "KiNG Nidhogg",
#                 "matchHistoryUri": "/v1/stats/player_history/NA1/200847956",
#                 "platformId": "NA1",
#                 "currentAccountId": "sYiz-Zgo9QJs0EtQupRCT8AMd6BEg2bZ_bGyNtBBLkrLggU",
#                 "profileIcon": 1413,
#                 "summonerId": "Sd3kfssuVXPZ8hl1p3BwIpJkICie_J2_nfTBU57O3Q-scos",
#                 "accountId": "sYiz-Zgo9QJs0EtQupRCT8AMd6BEg2bZ_bGyNtBBLkrLggU"
#             },
#             "participantId": 2
#         },
#         {
#             "player": {
#                 "currentPlatformId": "NA1",
#                 "summonerName": "dive top only",
#                 "matchHistoryUri": "/v1/stats/player_history/NA1/2397844919257632",
#                 "platformId": "NA1",
#                 "currentAccountId": "NqVM9Re0L6bwYdjiKgjFijBSq3OKANSb_8T1-R2wjzX7TPQTmzbwH31A",
#                 "profileIcon": 29,
#                 "summonerId": "To4Oab79ZEY_ay-hFNbxgSPdnrDGI4iKAEI62AWYKPpoL8UH",
#                 "accountId": "NqVM9Re0L6bwYdjiKgjFijBSq3OKANSb_8T1-R2wjzX7TPQTmzbwH31A"
#             },
#             "participantId": 3
#         },
#         {
#             "player": {
#                 "currentPlatformId": "NA1",
#                 "summonerName": "Kim Down",
#                 "matchHistoryUri": "/v1/stats/player_history/NA1/207458576",
#                 "platformId": "NA1",
#                 "currentAccountId": "esznF0c37QfpZoQkcr_Qe5_yRedXXNHqftvFOdOUYSi6SNw",
#                 "profileIcon": 595,
#                 "summonerId": "bdGCqc9wp06phHShys2auWZstSx8rem0VHXTuRZ9-pmVYwE",
#                 "accountId": "esznF0c37QfpZoQkcr_Qe5_yRedXXNHqftvFOdOUYSi6SNw"
#             },
#             "participantId": 4
#         },
#         {
#             "player": {
#                 "currentPlatformId": "NA1",
#                 "summonerName": "Quantum",
#                 "matchHistoryUri": "/v1/stats/player_history/NA1/244981925",
#                 "platformId": "NA1",
#                 "currentAccountId": "1xVBje2PU0Xy6jSjHZwvfqGqwHdXR2Ax3mUNAqSuO-jP24o",
#                 "profileIcon": 1637,
#                 "summonerId": "VaOXZjjNdlSyi9Gz1Rq5t_HJBCiTnhaHf5l2FJyosHZOhQ0",
#                 "accountId": "1xVBje2PU0Xy6jSjHZwvfqGqwHdXR2Ax3mUNAqSuO-jP24o"
#             },
#             "participantId": 5
#         },
#         {
#             "player": {
#                 "currentPlatformId": "NA1",
#                 "summonerName": "Liquid Impact",
#                 "matchHistoryUri": "/v1/stats/player_history/NA1/227437622",
#                 "platformId": "NA1",
#                 "currentAccountId": "2_hDcxI5NpAEER4RjmwNossoY-uSrQsqTC6CaN9fgvMI3Dc",
#                 "profileIcon": 7,
#                 "summonerId": "EXmmqkgIyofi28zO363Ge489Ih5hoqMpi7zk_RAdhtCxkDk",
#                 "accountId": "2_hDcxI5NpAEER4RjmwNossoY-uSrQsqTC6CaN9fgvMI3Dc"
#             },
#             "participantId": 6
#         },
#         {
#             "player": {
#                 "currentPlatformId": "NA1",
#                 "summonerName": "KhaliDino",
#                 "matchHistoryUri": "/v1/stats/player_history/EUN1/36176423",
#                 "platformId": "EUN1",
#                 "currentAccountId": "S1NXK-JzVc-_5ShUT2CHQKNQ9Cagcuyx7Alkv4nQ_jOIym0",
#                 "profileIcon": 4419,
#                 "summonerId": "rsD998V1wQskQEaSDvEHc5pFaYw62z8tAIPa4ClflywF6sI",
#                 "accountId": "05t_AYaUyyD5v0C6lKbwR9bXBDe4fl7gMZyzbuUY-yU8MQ"
#             },
#             "participantId": 7
#         },
#         {
#             "player": {
#                 "currentPlatformId": "NA1",
#                 "summonerName": " Myeongjin KR",
#                 "matchHistoryUri": "/v1/stats/player_history/NA1/2314614900354240",
#                 "platformId": "NA1",
#                 "currentAccountId": "u8sZUetxaCzTjZih3bja75Ufq2qjgxkWlyC3_aLlOgahmXfleO7YuhLT",
#                 "profileIcon": 2099,
#                 "summonerId": "8wXSBNKIj-6ffdyygUt8Ef7R0JMVWBjma21wvnep08nwMJC5",
#                 "accountId": "u8sZUetxaCzTjZih3bja75Ufq2qjgxkWlyC3_aLlOgahmXfleO7YuhLT"
#             },
#             "participantId": 8
#         },
#         {
#             "player": {
#                 "currentPlatformId": "NA1",
#                 "summonerName": "only jiao",
#                 "matchHistoryUri": "/v1/stats/player_history/NA1/215226854",
#                 "platformId": "NA1",
#                 "currentAccountId": "M4IG4h1RK-jZQ7TFh2npLnkRQL6Y4s7Y4jmVaYgccKDvm9A",
#                 "profileIcon": 15,
#                 "summonerId": "cWXzX7XnCV7qiew8WKZmHAKr2eoKggdrDrXj8uJaF5BBj7A",
#                 "accountId": "M4IG4h1RK-jZQ7TFh2npLnkRQL6Y4s7Y4jmVaYgccKDvm9A"
#             },
#             "participantId": 9
#         },
#         {
#             "player": {
#                 "currentPlatformId": "NA1",
#                 "summonerName": "PantsAreFacebook",
#                 "matchHistoryUri": "/v1/stats/player_history/NA1/235313317",
#                 "platformId": "NA1",
#                 "currentAccountId": "2RynWs0QZAAg8PqSKNf0mHqUr55JHwXn8vr491KAUbATETc",
#                 "profileIcon": 3587,
#                 "summonerId": "3YwlFyjsQxPhzC_a4ixVnK6YIj1xdK-LV_DhbrCFb0FgaKI",
#                 "accountId": "2RynWs0QZAAg8PqSKNf0mHqUr55JHwXn8vr491KAUbATETc"
#             },
#             "participantId": 10
#         }
#     ],
#     "gameVersion": "10.5.312.392",
#     "platformId": "NA1",
#     "gameMode": "CLASSIC",
#     "mapId": 11,
#     "gameType": "MATCHED_GAME",
#     "teams": [
#         {
#             "firstDragon": true,
#             "bans": [
#                 {
#                     "pickTurn": 1,
#                     "championId": 142
#                 },
#                 {
#                     "pickTurn": 2,
#                     "championId": 245
#                 },
#                 {
#                     "pickTurn": 3,
#                     "championId": 223
#                 },
#                 {
#                     "pickTurn": 4,
#                     "championId": 240
#                 },
#                 {
#                     "pickTurn": 5,
#                     "championId": 523
#                 }
#             ],
#             "firstInhibitor": true,
#             "win": "Win",
#             "firstRiftHerald": true,
#             "firstBaron": true,
#             "baronKills": 1,
#             "riftHeraldKills": 1,
#             "firstBlood": false,
#             "teamId": 100,
#             "firstTower": true,
#             "vilemawKills": 0,
#             "inhibitorKills": 2,
#             "towerKills": 10,
#             "dominionVictoryScore": 0,
#             "dragonKills": 4
#         },
#         {
#             "firstDragon": false,
#             "bans": [
#                 {
#                     "pickTurn": 6,
#                     "championId": 523
#                 },
#                 {
#                     "pickTurn": 7,
#                     "championId": 7
#                 },
#                 {
#                     "pickTurn": 8,
#                     "championId": 350
#                 },
#                 {
#                     "pickTurn": 9,
#                     "championId": 157
#                 },
#                 {
#                     "pickTurn": 10,
#                     "championId": 107
#                 }
#             ],
#             "firstInhibitor": false,
#             "win": "Fail",
#             "firstRiftHerald": false,
#             "firstBaron": false,
#             "baronKills": 0,
#             "riftHeraldKills": 0,
#             "firstBlood": true,
#             "teamId": 200,
#             "firstTower": false,
#             "vilemawKills": 0,
#             "inhibitorKills": 0,
#             "towerKills": 0,
#             "dominionVictoryScore": 0,
#             "dragonKills": 0
#         }
#     ],
#     "participants": [
#         {
#             "spell1Id": 4,
#             "participantId": 1,
#             "timeline": {
#                 "lane": "BOTTOM",
#                 "participantId": 1,
#                 "csDiffPerMinDeltas": {
#                     "0-10": 1.2,
#                     "10-20": 0.4000000000000006
#                 },
#                 "goldPerMinDeltas": {
#                     "0-10": 315.8,
#                     "10-20": 498.4
#                 },
#                 "xpDiffPerMinDeltas": {
#                     "0-10": 92.70000000000002,
#                     "10-20": 0.6999999999999886
#                 },
#                 "creepsPerMinDeltas": {
#                     "0-10": 7.9,
#                     "10-20": 7.800000000000001
#                 },
#                 "xpPerMinDeltas": {
#                     "0-10": 360.1,
#                     "10-20": 539.2
#                 },
#                 "role": "DUO_CARRY",
#                 "damageTakenDiffPerMinDeltas": {
#                     "0-10": -47.80000000000002,
#                     "10-20": 119.80000000000007
#                 },
#                 "damageTakenPerMinDeltas": {
#                     "0-10": 226.89999999999998,
#                     "10-20": 546.6
#                 }
#             },
#             "spell2Id": 12,
#             "teamId": 100,
#             "stats": {
#                 "neutralMinionsKilledTeamJungle": 12,
#                 "visionScore": 23,
#                 "magicDamageDealtToChampions": 17805,
#                 "largestMultiKill": 1,
#                 "totalTimeCrowdControlDealt": 225,
#                 "longestTimeSpentLiving": 557,
#                 "perk1Var1": 835,
#                 "perk1Var3": 0,
#                 "perk1Var2": 0,
#                 "tripleKills": 0,
#                 "perk5": 8210,
#                 "perk4": 8226,
#                 "playerScore9": 0,
#                 "playerScore8": 0,
#                 "kills": 3,
#                 "playerScore1": 0,
#                 "playerScore0": 0,
#                 "playerScore3": 0,
#                 "playerScore2": 0,
#                 "playerScore5": 0,
#                 "playerScore4": 0,
#                 "playerScore7": 0,
#                 "playerScore6": 1,
#                 "perk5Var1": 0,
#                 "perk5Var3": 0,
#                 "perk5Var2": 0,
#                 "totalScoreRank": 0,
#                 "neutralMinionsKilled": 16,
#                 "statPerk1": 5008,
#                 "statPerk0": 5008,
#                 "damageDealtToTurrets": 3891,
#                 "physicalDamageDealtToChampions": 739,
#                 "damageDealtToObjectives": 6126,
#                 "perk2Var2": 0,
#                 "perk2Var3": 0,
#                 "totalUnitsHealed": 1,
#                 "perk2Var1": 30,
#                 "perk4Var1": 250,
#                 "totalDamageTaken": 17772,
#                 "perk4Var3": 0,
#                 "wardsKilled": 5,
#                 "largestCriticalStrike": 0,
#                 "largestKillingSpree": 0,
#                 "quadraKills": 0,
#                 "magicDamageDealt": 126677,
#                 "firstBloodAssist": false,
#                 "item2": 3165,
#                 "item3": 3136,
#                 "item0": 3030,
#                 "item1": 3157,
#                 "item6": 3363,
#                 "item4": 2055,
#                 "item5": 3020,
#                 "perk1": 8139,
#                 "perk0": 8112,
#                 "perk3": 8135,
#                 "perk2": 8138,
#                 "perk3Var3": 0,
#                 "perk3Var2": 5,
#                 "perk3Var1": 2754,
#                 "damageSelfMitigated": 11251,
#                 "magicalDamageTaken": 6938,
#                 "perk0Var2": 0,
#                 "firstInhibitorKill": false,
#                 "trueDamageTaken": 314,
#                 "assists": 14,
#                 "perk4Var2": 1114,
#                 "goldSpent": 12250,
#                 "trueDamageDealt": 2605,
#                 "participantId": 1,
#                 "physicalDamageDealt": 11334,
#                 "sightWardsBoughtInGame": 0,
#                 "totalDamageDealtToChampions": 18545,
#                 "physicalDamageTaken": 10519,
#                 "totalPlayerScore": 0,
#                 "win": true,
#                 "objectivePlayerScore": 0,
#                 "totalDamageDealt": 140617,
#                 "neutralMinionsKilledEnemyJungle": 0,
#                 "deaths": 6,
#                 "wardsPlaced": 6,
#                 "perkPrimaryStyle": 8100,
#                 "perkSubStyle": 8200,
#                 "turretKills": 3,
#                 "firstBloodKill": false,
#                 "trueDamageDealtToChampions": 0,
#                 "goldEarned": 12627,
#                 "killingSprees": 0,
#                 "unrealKills": 0,
#                 "firstTowerAssist": true,
#                 "firstTowerKill": false,
#                 "champLevel": 15,
#                 "doubleKills": 0,
#                 "inhibitorKills": 0,
#                 "firstInhibitorAssist": true,
#                 "perk0Var1": 764,
#                 "combatPlayerScore": 0,
#                 "perk0Var3": 0,
#                 "visionWardsBoughtInGame": 4,
#                 "pentaKills": 0,
#                 "totalHeal": 4681,
#                 "totalMinionsKilled": 196,
#                 "timeCCingOthers": 23,
#                 "statPerk2": 5002
#             },
#             "championId": 134
#         },
#         {
#             "spell1Id": 11,
#             "participantId": 2,
#             "timeline": {
#                 "lane": "JUNGLE",
#                 "participantId": 2,
#                 "csDiffPerMinDeltas": {
#                     "0-10": 0.30000000000000004,
#                     "10-20": 0.9
#                 },
#                 "goldPerMinDeltas": {
#                     "0-10": 428.9,
#                     "10-20": 437.29999999999995
#                 },
#                 "xpDiffPerMinDeltas": {
#                     "0-10": 162.70000000000002,
#                     "10-20": 72.89999999999998
#                 },
#                 "creepsPerMinDeltas": {
#                     "0-10": 0.8,
#                     "10-20": 1
#                 },
#                 "xpPerMinDeltas": {
#                     "0-10": 425.8,
#                     "10-20": 549.3
#                 },
#                 "role": "NONE",
#                 "damageTakenDiffPerMinDeltas": {
#                     "0-10": -392.9,
#                     "10-20": -351.99999999999994
#                 },
#                 "damageTakenPerMinDeltas": {
#                     "0-10": 438.6,
#                     "10-20": 886.3
#                 }
#             },
#             "spell2Id": 4,
#             "teamId": 100,
#             "stats": {
#                 "neutralMinionsKilledTeamJungle": 80,
#                 "visionScore": 30,
#                 "magicDamageDealtToChampions": 1861,
#                 "largestMultiKill": 3,
#                 "totalTimeCrowdControlDealt": 389,
#                 "longestTimeSpentLiving": 878,
#                 "perk1Var1": 1135,
#                 "perk1Var3": 0,
#                 "perk1Var2": 440,
#                 "tripleKills": 1,
#                 "perk5": 8304,
#                 "perk4": 8347,
#                 "playerScore9": 0,
#                 "playerScore8": 0,
#                 "kills": 11,
#                 "playerScore1": 0,
#                 "playerScore0": 0,
#                 "playerScore3": 0,
#                 "playerScore2": 0,
#                 "playerScore5": 0,
#                 "playerScore4": 0,
#                 "playerScore7": 0,
#                 "playerScore6": 1,
#                 "perk5Var1": 9,
#                 "perk5Var3": 0,
#                 "perk5Var2": 0,
#                 "totalScoreRank": 0,
#                 "neutralMinionsKilled": 166,
#                 "statPerk1": 5008,
#                 "statPerk0": 5005,
#                 "damageDealtToTurrets": 2018,
#                 "physicalDamageDealtToChampions": 19782,
#                 "damageDealtToObjectives": 44888,
#                 "perk2Var2": 10,
#                 "perk2Var3": 0,
#                 "totalUnitsHealed": 1,
#                 "perk2Var1": 10,
#                 "perk4Var1": 0,
#                 "totalDamageTaken": 29128,
#                 "perk4Var3": 0,
#                 "wardsKilled": 2,
#                 "largestCriticalStrike": 0,
#                 "largestKillingSpree": 6,
#                 "quadraKills": 0,
#                 "magicDamageDealt": 30927,
#                 "firstBloodAssist": false,
#                 "item2": 3071,
#                 "item3": 3156,
#                 "item0": 1412,
#                 "item1": 3111,
#                 "item6": 3340,
#                 "item4": 3074,
#                 "item5": 0,
#                 "perk1": 9111,
#                 "perk0": 8010,
#                 "perk3": 8014,
#                 "perk2": 9104,
#                 "perk3Var3": 0,
#                 "perk3Var2": 0,
#                 "perk3Var1": 421,
#                 "damageSelfMitigated": 30012,
#                 "magicalDamageTaken": 6523,
#                 "perk0Var2": 0,
#                 "firstInhibitorKill": false,
#                 "trueDamageTaken": 760,
#                 "assists": 11,
#                 "perk4Var2": 0,
#                 "goldSpent": 14200,
#                 "trueDamageDealt": 15069,
#                 "participantId": 2,
#                 "physicalDamageDealt": 160641,
#                 "sightWardsBoughtInGame": 0,
#                 "totalDamageDealtToChampions": 22718,
#                 "physicalDamageTaken": 21843,
#                 "totalPlayerScore": 0,
#                 "win": true,
#                 "objectivePlayerScore": 0,
#                 "totalDamageDealt": 206637,
#                 "neutralMinionsKilledEnemyJungle": 29,
#                 "deaths": 3,
#                 "wardsPlaced": 11,
#                 "perkPrimaryStyle": 8000,
#                 "perkSubStyle": 8300,
#                 "turretKills": 1,
#                 "firstBloodKill": false,
#                 "trueDamageDealtToChampions": 1075,
#                 "goldEarned": 13921,
#                 "killingSprees": 2,
#                 "unrealKills": 0,
#                 "firstTowerAssist": false,
#                 "firstTowerKill": true,
#                 "champLevel": 16,
#                 "doubleKills": 2,
#                 "inhibitorKills": 1,
#                 "firstInhibitorAssist": false,
#                 "perk0Var1": 1171,
#                 "combatPlayerScore": 0,
#                 "perk0Var3": 0,
#                 "visionWardsBoughtInGame": 3,
#                 "pentaKills": 0,
#                 "totalHeal": 9341,
#                 "totalMinionsKilled": 33,
#                 "timeCCingOthers": 20,
#                 "statPerk2": 5002
#             },
#             "championId": 64
#         },
#         {
#             "spell1Id": 4,
#             "participantId": 3,
#             "timeline": {
#                 "lane": "TOP",
#                 "participantId": 3,
#                 "csDiffPerMinDeltas": {
#                     "0-10": 1.6999999999999997,
#                     "10-20": 1.7999999999999998
#                 },
#                 "goldPerMinDeltas": {
#                     "0-10": 304.3,
#                     "10-20": 648.1
#                 },
#                 "xpDiffPerMinDeltas": {
#                     "0-10": 1.200000000000017,
#                     "10-20": 216.50000000000003
#                 },
#                 "creepsPerMinDeltas": {
#                     "0-10": 7.4,
#                     "10-20": 8.3
#                 },
#                 "xpPerMinDeltas": {
#                     "0-10": 449.5,
#                     "10-20": 693.8
#                 },
#                 "role": "SOLO",
#                 "damageTakenDiffPerMinDeltas": {
#                     "0-10": 53.400000000000006,
#                     "10-20": -133.9000000000001
#                 },
#                 "damageTakenPerMinDeltas": {
#                     "0-10": 550.7,
#                     "10-20": 1337.1999999999998
#                 }
#             },
#             "spell2Id": 12,
#             "teamId": 100,
#             "stats": {
#                 "neutralMinionsKilledTeamJungle": 5,
#                 "visionScore": 22,
#                 "magicDamageDealtToChampions": 12996,
#                 "largestMultiKill": 4,
#                 "totalTimeCrowdControlDealt": 183,
#                 "longestTimeSpentLiving": 675,
#                 "perk1Var1": 5159,
#                 "perk1Var3": 0,
#                 "perk1Var2": 5366,
#                 "tripleKills": 1,
#                 "perk5": 8345,
#                 "perk4": 8352,
#                 "playerScore9": 0,
#                 "playerScore8": 0,
#                 "kills": 17,
#                 "playerScore1": 0,
#                 "playerScore0": 0,
#                 "playerScore3": 0,
#                 "playerScore2": 0,
#                 "playerScore5": 0,
#                 "playerScore4": 0,
#                 "playerScore7": 0,
#                 "playerScore6": 1,
#                 "perk5Var1": 3,
#                 "perk5Var3": 0,
#                 "perk5Var2": 0,
#                 "totalScoreRank": 0,
#                 "neutralMinionsKilled": 16,
#                 "statPerk1": 5008,
#                 "statPerk0": 5005,
#                 "damageDealtToTurrets": 7304,
#                 "physicalDamageDealtToChampions": 26446,
#                 "damageDealtToObjectives": 16606,
#                 "perk2Var2": 50,
#                 "perk2Var3": 0,
#                 "totalUnitsHealed": 1,
#                 "perk2Var1": 11,
#                 "perk4Var1": 326,
#                 "totalDamageTaken": 32543,
#                 "perk4Var3": 986,
#                 "wardsKilled": 2,
#                 "largestCriticalStrike": 0,
#                 "largestKillingSpree": 7,
#                 "quadraKills": 1,
#                 "magicDamageDealt": 52565,
#                 "firstBloodAssist": false,
#                 "item2": 3153,
#                 "item3": 3047,
#                 "item0": 3044,
#                 "item1": 3091,
#                 "item6": 3364,
#                 "item4": 3067,
#                 "item5": 3053,
#                 "perk1": 9101,
#                 "perk0": 8010,
#                 "perk3": 8014,
#                 "perk2": 9105,
#                 "perk3Var3": 0,
#                 "perk3Var2": 0,
#                 "perk3Var1": 1163,
#                 "damageSelfMitigated": 34936,
#                 "magicalDamageTaken": 6515,
#                 "perk0Var2": 0,
#                 "firstInhibitorKill": false,
#                 "trueDamageTaken": 1287,
#                 "assists": 10,
#                 "perk4Var2": 1476,
#                 "goldSpent": 13650,
#                 "trueDamageDealt": 4428,
#                 "participantId": 3,
#                 "physicalDamageDealt": 162399,
#                 "sightWardsBoughtInGame": 0,
#                 "totalDamageDealtToChampions": 39688,
#                 "physicalDamageTaken": 24740,
#                 "totalPlayerScore": 0,
#                 "win": true,
#                 "objectivePlayerScore": 0,
#                 "totalDamageDealt": 219393,
#                 "neutralMinionsKilledEnemyJungle": 6,
#                 "deaths": 4,
#                 "wardsPlaced": 8,
#                 "perkPrimaryStyle": 8000,
#                 "perkSubStyle": 8300,
#                 "turretKills": 3,
#                 "firstBloodKill": false,
#                 "trueDamageDealtToChampions": 246,
#                 "goldEarned": 16973,
#                 "killingSprees": 3,
#                 "unrealKills": 0,
#                 "firstTowerAssist": false,
#                 "firstTowerKill": false,
#                 "champLevel": 18,
#                 "doubleKills": 3,
#                 "inhibitorKills": 0,
#                 "firstInhibitorAssist": true,
#                 "perk0Var1": 3115,
#                 "combatPlayerScore": 0,
#                 "perk0Var3": 0,
#                 "visionWardsBoughtInGame": 2,
#                 "pentaKills": 0,
#                 "totalHeal": 12416,
#                 "totalMinionsKilled": 238,
#                 "timeCCingOthers": 23,
#                 "statPerk2": 5002
#             },
#             "championId": 39
#         },
#         {
#             "spell1Id": 14,
#             "participantId": 4,
#             "timeline": {
#                 "lane": "BOTTOM",
#                 "participantId": 4,
#                 "csDiffPerMinDeltas": {
#                     "0-10": 1.2,
#                     "10-20": 0.4000000000000006
#                 },
#                 "goldPerMinDeltas": {
#                     "0-10": 238.2,
#                     "10-20": 265.9
#                 },
#                 "xpDiffPerMinDeltas": {
#                     "0-10": 92.70000000000002,
#                     "10-20": 0.6999999999999886
#                 },
#                 "creepsPerMinDeltas": {
#                     "0-10": 1.3,
#                     "10-20": 0.9
#                 },
#                 "xpPerMinDeltas": {
#                     "0-10": 360.6,
#                     "10-20": 253
#                 },
#                 "role": "DUO_SUPPORT",
#                 "damageTakenDiffPerMinDeltas": {
#                     "0-10": -47.80000000000002,
#                     "10-20": 119.80000000000007
#                 },
#                 "damageTakenPerMinDeltas": {
#                     "0-10": 290,
#                     "10-20": 578.2
#                 }
#             },
#             "spell2Id": 4,
#             "teamId": 100,
#             "stats": {
#                 "neutralMinionsKilledTeamJungle": 0,
#                 "visionScore": 70,
#                 "magicDamageDealtToChampions": 6328,
#                 "largestMultiKill": 2,
#                 "totalTimeCrowdControlDealt": 209,
#                 "longestTimeSpentLiving": 766,
#                 "perk1Var1": 1147,
#                 "perk1Var3": 0,
#                 "perk1Var2": 0,
#                 "tripleKills": 0,
#                 "perk5": 8345,
#                 "perk4": 8313,
#                 "playerScore9": 0,
#                 "playerScore8": 0,
#                 "kills": 3,
#                 "playerScore1": 0,
#                 "playerScore0": 0,
#                 "playerScore3": 0,
#                 "playerScore2": 0,
#                 "playerScore5": 0,
#                 "playerScore4": 0,
#                 "playerScore7": 0,
#                 "playerScore6": 1,
#                 "perk5Var1": 3,
#                 "perk5Var3": 0,
#                 "perk5Var2": 0,
#                 "totalScoreRank": 0,
#                 "neutralMinionsKilled": 0,
#                 "statPerk1": 5002,
#                 "statPerk0": 5008,
#                 "damageDealtToTurrets": 2034,
#                 "physicalDamageDealtToChampions": 2425,
#                 "damageDealtToObjectives": 2034,
#                 "perk2Var2": 0,
#                 "perk2Var3": 0,
#                 "totalUnitsHealed": 1,
#                 "perk2Var1": 565,
#                 "perk4Var1": 0,
#                 "totalDamageTaken": 16975,
#                 "perk4Var3": 0,
#                 "wardsKilled": 6,
#                 "largestCriticalStrike": 0,
#                 "largestKillingSpree": 2,
#                 "quadraKills": 0,
#                 "magicDamageDealt": 10652,
#                 "firstBloodAssist": false,
#                 "item2": 2055,
#                 "item3": 3105,
#                 "item0": 3193,
#                 "item1": 3860,
#                 "item6": 3364,
#                 "item4": 3117,
#                 "item5": 3050,
#                 "perk1": 8446,
#                 "perk0": 8439,
#                 "perk3": 8242,
#                 "perk2": 8473,
#                 "perk3Var3": 0,
#                 "perk3Var2": 0,
#                 "perk3Var1": 10,
#                 "damageSelfMitigated": 35308,
#                 "magicalDamageTaken": 4889,
#                 "perk0Var2": 0,
#                 "firstInhibitorKill": false,
#                 "trueDamageTaken": 70,
#                 "assists": 18,
#                 "perk4Var2": 0,
#                 "goldSpent": 8300,
#                 "trueDamageDealt": 6556,
#                 "participantId": 4,
#                 "physicalDamageDealt": 8523,
#                 "sightWardsBoughtInGame": 0,
#                 "totalDamageDealtToChampions": 9334,
#                 "physicalDamageTaken": 12015,
#                 "totalPlayerScore": 0,
#                 "win": true,
#                 "objectivePlayerScore": 0,
#                 "totalDamageDealt": 25732,
#                 "neutralMinionsKilledEnemyJungle": 0,
#                 "deaths": 4,
#                 "wardsPlaced": 43,
#                 "perkPrimaryStyle": 8400,
#                 "perkSubStyle": 8300,
#                 "turretKills": 0,
#                 "firstBloodKill": false,
#                 "trueDamageDealtToChampions": 580,
#                 "goldEarned": 9924,
#                 "killingSprees": 1,
#                 "unrealKills": 0,
#                 "firstTowerAssist": false,
#                 "firstTowerKill": false,
#                 "champLevel": 15,
#                 "doubleKills": 1,
#                 "inhibitorKills": 0,
#                 "firstInhibitorAssist": true,
#                 "perk0Var1": 668,
#                 "combatPlayerScore": 0,
#                 "perk0Var3": 0,
#                 "visionWardsBoughtInGame": 14,
#                 "pentaKills": 0,
#                 "totalHeal": 2273,
#                 "totalMinionsKilled": 28,
#                 "timeCCingOthers": 50,
#                 "statPerk2": 5001
#             },
#             "championId": 111
#         },
#         {
#             "spell1Id": 4,
#             "participantId": 5,
#             "timeline": {
#                 "lane": "MIDDLE",
#                 "participantId": 5,
#                 "csDiffPerMinDeltas": {
#                     "0-10": 0.2999999999999998,
#                     "10-20": -4.800000000000001
#                 },
#                 "goldPerMinDeltas": {
#                     "0-10": 247.8,
#                     "10-20": 393.4
#                 },
#                 "xpDiffPerMinDeltas": {
#                     "0-10": -34.099999999999994,
#                     "10-20": -255.8
#                 },
#                 "creepsPerMinDeltas": {
#                     "0-10": 7.199999999999999,
#                     "10-20": 4.1
#                 },
#                 "xpPerMinDeltas": {
#                     "0-10": 428.3,
#                     "10-20": 435.09999999999997
#                 },
#                 "role": "SOLO",
#                 "damageTakenDiffPerMinDeltas": {
#                     "0-10": -77.80000000000001,
#                     "10-20": 172.4
#                 },
#                 "damageTakenPerMinDeltas": {
#                     "0-10": 236.89999999999998,
#                     "10-20": 717.7
#                 }
#             },
#             "spell2Id": 14,
#             "teamId": 100,
#             "stats": {
#                 "neutralMinionsKilledTeamJungle": 0,
#                 "visionScore": 27,
#                 "magicDamageDealtToChampions": 0,
#                 "largestMultiKill": 2,
#                 "totalTimeCrowdControlDealt": 126,
#                 "longestTimeSpentLiving": 950,
#                 "perk1Var1": 603,
#                 "perk1Var3": 0,
#                 "perk1Var2": 0,
#                 "tripleKills": 0,
#                 "perk5": 8453,
#                 "perk4": 8473,
#                 "playerScore9": 0,
#                 "playerScore8": 0,
#                 "kills": 10,
#                 "playerScore1": 0,
#                 "playerScore0": 0,
#                 "playerScore3": 0,
#                 "playerScore2": 0,
#                 "playerScore5": 0,
#                 "playerScore4": 0,
#                 "playerScore7": 0,
#                 "playerScore6": 1,
#                 "perk5Var1": 510,
#                 "perk5Var3": 0,
#                 "perk5Var2": 87,
#                 "totalScoreRank": 0,
#                 "neutralMinionsKilled": 0,
#                 "statPerk1": 5008,
#                 "statPerk0": 5008,
#                 "damageDealtToTurrets": 2098,
#                 "physicalDamageDealtToChampions": 10932,
#                 "damageDealtToObjectives": 3905,
#                 "perk2Var2": 0,
#                 "perk2Var3": 0,
#                 "totalUnitsHealed": 1,
#                 "perk2Var1": 18,
#                 "perk4Var1": 526,
#                 "totalDamageTaken": 16237,
#                 "perk4Var3": 0,
#                 "wardsKilled": 5,
#                 "largestCriticalStrike": 0,
#                 "largestKillingSpree": 8,
#                 "quadraKills": 0,
#                 "magicDamageDealt": 0,
#                 "firstBloodAssist": false,
#                 "item2": 3077,
#                 "item3": 3142,
#                 "item0": 3009,
#                 "item1": 3147,
#                 "item6": 3340,
#                 "item4": 3814,
#                 "item5": 3071,
#                 "perk1": 8126,
#                 "perk0": 9923,
#                 "perk3": 8106,
#                 "perk2": 8138,
#                 "perk3Var3": 0,
#                 "perk3Var2": 0,
#                 "perk3Var1": 5,
#                 "damageSelfMitigated": 13108,
#                 "magicalDamageTaken": 6671,
#                 "perk0Var2": 65,
#                 "firstInhibitorKill": false,
#                 "trueDamageTaken": 128,
#                 "assists": 6,
#                 "perk4Var2": 0,
#                 "goldSpent": 14375,
#                 "trueDamageDealt": 5278,
#                 "participantId": 5,
#                 "physicalDamageDealt": 65750,
#                 "sightWardsBoughtInGame": 0,
#                 "totalDamageDealtToChampions": 14568,
#                 "physicalDamageTaken": 9438,
#                 "totalPlayerScore": 0,
#                 "win": true,
#                 "objectivePlayerScore": 0,
#                 "totalDamageDealt": 71028,
#                 "neutralMinionsKilledEnemyJungle": 0,
#                 "deaths": 2,
#                 "wardsPlaced": 12,
#                 "perkPrimaryStyle": 8100,
#                 "perkSubStyle": 8400,
#                 "turretKills": 2,
#                 "firstBloodKill": false,
#                 "trueDamageDealtToChampions": 3636,
#                 "goldEarned": 14393,
#                 "killingSprees": 2,
#                 "unrealKills": 0,
#                 "firstTowerAssist": false,
#                 "firstTowerKill": false,
#                 "champLevel": 16,
#                 "doubleKills": 2,
#                 "inhibitorKills": 0,
#                 "firstInhibitorAssist": false,
#                 "perk0Var1": 39,
#                 "combatPlayerScore": 0,
#                 "perk0Var3": 0,
#                 "visionWardsBoughtInGame": 4,
#                 "pentaKills": 0,
#                 "totalHeal": 5893,
#                 "totalMinionsKilled": 148,
#                 "timeCCingOthers": 13,
#                 "statPerk2": 5003
#             },
#             "championId": 555
#         },
#         {
#             "spell1Id": 4,
#             "participantId": 6,
#             "timeline": {
#                 "lane": "TOP",
#                 "participantId": 6,
#                 "csDiffPerMinDeltas": {
#                     "0-10": -1.6999999999999997,
#                     "10-20": -1.7999999999999998
#                 },
#                 "goldPerMinDeltas": {
#                     "0-10": 256.9,
#                     "10-20": 319.4
#                 },
#                 "xpDiffPerMinDeltas": {
#                     "0-10": -1.200000000000017,
#                     "10-20": -216.50000000000003
#                 },
#                 "creepsPerMinDeltas": {
#                     "0-10": 5.7,
#                     "10-20": 6.5
#                 },
#                 "xpPerMinDeltas": {
#                     "0-10": 448.29999999999995,
#                     "10-20": 477.29999999999995
#                 },
#                 "role": "SOLO",
#                 "damageTakenDiffPerMinDeltas": {
#                     "0-10": -53.400000000000006,
#                     "10-20": 133.9000000000001
#                 },
#                 "damageTakenPerMinDeltas": {
#                     "0-10": 497.29999999999995,
#                     "10-20": 1471.1
#                 }
#             },
#             "spell2Id": 12,
#             "teamId": 200,
#             "stats": {
#                 "neutralMinionsKilledTeamJungle": 14,
#                 "visionScore": 25,
#                 "magicDamageDealtToChampions": 0,
#                 "largestMultiKill": 2,
#                 "totalTimeCrowdControlDealt": 239,
#                 "longestTimeSpentLiving": 356,
#                 "perk1Var1": 913,
#                 "perk1Var3": 0,
#                 "perk1Var2": 160,
#                 "tripleKills": 0,
#                 "perk5": 8135,
#                 "perk4": 8139,
#                 "playerScore9": 0,
#                 "playerScore8": 0,
#                 "kills": 6,
#                 "playerScore1": 0,
#                 "playerScore0": 0,
#                 "playerScore3": 0,
#                 "playerScore2": 0,
#                 "playerScore5": 0,
#                 "playerScore4": 0,
#                 "playerScore7": 0,
#                 "playerScore6": 0,
#                 "perk5Var1": 1338,
#                 "perk5Var3": 0,
#                 "perk5Var2": 4,
#                 "totalScoreRank": 0,
#                 "neutralMinionsKilled": 16,
#                 "statPerk1": 5008,
#                 "statPerk0": 5008,
#                 "damageDealtToTurrets": 1606,
#                 "physicalDamageDealtToChampions": 21458,
#                 "damageDealtToObjectives": 2910,
#                 "perk2Var2": 50,
#                 "perk2Var3": 0,
#                 "totalUnitsHealed": 1,
#                 "perk2Var1": 24,
#                 "perk4Var1": 968,
#                 "totalDamageTaken": 40386,
#                 "perk4Var3": 0,
#                 "wardsKilled": 1,
#                 "largestCriticalStrike": 0,
#                 "largestKillingSpree": 2,
#                 "quadraKills": 0,
#                 "magicDamageDealt": 0,
#                 "firstBloodAssist": false,
#                 "item2": 3123,
#                 "item3": 3071,
#                 "item0": 1055,
#                 "item1": 3067,
#                 "item6": 3340,
#                 "item4": 3053,
#                 "item5": 3047,
#                 "perk1": 9111,
#                 "perk0": 8010,
#                 "perk3": 8299,
#                 "perk2": 9104,
#                 "perk3Var3": 0,
#                 "perk3Var2": 0,
#                 "perk3Var1": 810,
#                 "damageSelfMitigated": 29203,
#                 "magicalDamageTaken": 12340,
#                 "perk0Var2": 0,
#                 "firstInhibitorKill": false,
#                 "trueDamageTaken": 888,
#                 "assists": 2,
#                 "perk4Var2": 0,
#                 "goldSpent": 9775,
#                 "trueDamageDealt": 288,
#                 "participantId": 6,
#                 "physicalDamageDealt": 118347,
#                 "sightWardsBoughtInGame": 0,
#                 "totalDamageDealtToChampions": 21746,
#                 "physicalDamageTaken": 27157,
#                 "totalPlayerScore": 0,
#                 "win": false,
#                 "objectivePlayerScore": 0,
#                 "totalDamageDealt": 118635,
#                 "neutralMinionsKilledEnemyJungle": 0,
#                 "deaths": 10,
#                 "wardsPlaced": 12,
#                 "perkPrimaryStyle": 8000,
#                 "perkSubStyle": 8100,
#                 "turretKills": 0,
#                 "firstBloodKill": true,
#                 "trueDamageDealtToChampions": 288,
#                 "goldEarned": 10998,
#                 "killingSprees": 1,
#                 "unrealKills": 0,
#                 "firstTowerAssist": false,
#                 "firstTowerKill": false,
#                 "champLevel": 15,
#                 "doubleKills": 1,
#                 "inhibitorKills": 0,
#                 "firstInhibitorAssist": false,
#                 "perk0Var1": 1312,
#                 "combatPlayerScore": 0,
#                 "perk0Var3": 0,
#                 "visionWardsBoughtInGame": 4,
#                 "pentaKills": 0,
#                 "totalHeal": 13712,
#                 "totalMinionsKilled": 159,
#                 "timeCCingOthers": 26,
#                 "statPerk2": 5002
#             },
#             "championId": 266
#         },
#         {
#             "spell1Id": 3,
#             "participantId": 7,
#             "timeline": {
#                 "lane": "BOTTOM",
#                 "participantId": 7,
#                 "csDiffPerMinDeltas": {
#                     "0-10": -1.2,
#                     "10-20": -0.4000000000000006
#                 },
#                 "goldPerMinDeltas": {
#                     "0-10": 172.7,
#                     "10-20": 316.9
#                 },
#                 "xpDiffPerMinDeltas": {
#                     "0-10": -92.70000000000002,
#                     "10-20": -0.6999999999999886
#                 },
#                 "creepsPerMinDeltas": {
#                     "0-10": 0.30000000000000004,
#                     "10-20": 1.9
#                 },
#                 "xpPerMinDeltas": {
#                     "0-10": 261.6,
#                     "10-20": 363.7
#                 },
#                 "role": "DUO_SUPPORT",
#                 "damageTakenDiffPerMinDeltas": {
#                     "0-10": 47.80000000000002,
#                     "10-20": -119.80000000000007
#                 },
#                 "damageTakenPerMinDeltas": {
#                     "0-10": 310.1,
#                     "10-20": 362.5
#                 }
#             },
#             "spell2Id": 4,
#             "teamId": 200,
#             "stats": {
#                 "neutralMinionsKilledTeamJungle": 0,
#                 "visionScore": 66,
#                 "magicDamageDealtToChampions": 0,
#                 "largestMultiKill": 1,
#                 "totalTimeCrowdControlDealt": 169,
#                 "longestTimeSpentLiving": 402,
#                 "perk1Var1": 11,
#                 "perk1Var3": 5,
#                 "perk1Var2": 1,
#                 "tripleKills": 0,
#                 "perk5": 8014,
#                 "perk4": 8009,
#                 "playerScore9": 0,
#                 "playerScore8": 0,
#                 "kills": 2,
#                 "playerScore1": 0,
#                 "playerScore0": 0,
#                 "playerScore3": 0,
#                 "playerScore2": 0,
#                 "playerScore5": 0,
#                 "playerScore4": 0,
#                 "playerScore7": 0,
#                 "playerScore6": 0,
#                 "perk5Var1": 183,
#                 "perk5Var3": 0,
#                 "perk5Var2": 0,
#                 "totalScoreRank": 0,
#                 "neutralMinionsKilled": 0,
#                 "statPerk1": 5002,
#                 "statPerk0": 5008,
#                 "damageDealtToTurrets": 384,
#                 "physicalDamageDealtToChampions": 11165,
#                 "damageDealtToObjectives": 384,
#                 "perk2Var2": 0,
#                 "perk2Var3": 0,
#                 "totalUnitsHealed": 5,
#                 "perk2Var1": 3,
#                 "perk4Var1": 1149,
#                 "totalDamageTaken": 14061,
#                 "perk4Var3": 0,
#                 "wardsKilled": 15,
#                 "largestCriticalStrike": 308,
#                 "largestKillingSpree": 2,
#                 "quadraKills": 0,
#                 "magicDamageDealt": 0,
#                 "firstBloodAssist": false,
#                 "item2": 3155,
#                 "item3": 3158,
#                 "item0": 3864,
#                 "item1": 3179,
#                 "item6": 3364,
#                 "item4": 3123,
#                 "item5": 1031,
#                 "perk1": 8304,
#                 "perk0": 8351,
#                 "perk3": 8410,
#                 "perk2": 8345,
#                 "perk3Var3": 0,
#                 "perk3Var2": 0,
#                 "perk3Var1": 82,
#                 "damageSelfMitigated": 10763,
#                 "magicalDamageTaken": 5575,
#                 "perk0Var2": 0,
#                 "firstInhibitorKill": false,
#                 "trueDamageTaken": 634,
#                 "assists": 9,
#                 "perk4Var2": 500,
#                 "goldSpent": 6775,
#                 "trueDamageDealt": 166,
#                 "participantId": 7,
#                 "physicalDamageDealt": 24585,
#                 "sightWardsBoughtInGame": 0,
#                 "totalDamageDealtToChampions": 11237,
#                 "physicalDamageTaken": 7851,
#                 "totalPlayerScore": 0,
#                 "win": false,
#                 "objectivePlayerScore": 0,
#                 "totalDamageDealt": 24751,
#                 "neutralMinionsKilledEnemyJungle": 0,
#                 "deaths": 9,
#                 "wardsPlaced": 22,
#                 "perkPrimaryStyle": 8300,
#                 "perkSubStyle": 8000,
#                 "turretKills": 0,
#                 "firstBloodKill": false,
#                 "trueDamageDealtToChampions": 72,
#                 "goldEarned": 7311,
#                 "killingSprees": 1,
#                 "unrealKills": 0,
#                 "firstTowerAssist": false,
#                 "firstTowerKill": false,
#                 "champLevel": 13,
#                 "doubleKills": 0,
#                 "inhibitorKills": 0,
#                 "firstInhibitorAssist": false,
#                 "perk0Var1": 45,
#                 "combatPlayerScore": 0,
#                 "perk0Var3": 0,
#                 "visionWardsBoughtInGame": 4,
#                 "pentaKills": 0,
#                 "totalHeal": 5162,
#                 "totalMinionsKilled": 30,
#                 "timeCCingOthers": 53,
#                 "statPerk2": 5002
#             },
#             "championId": 235
#         },
#         {
#             "spell1Id": 7,
#             "participantId": 8,
#             "timeline": {
#                 "lane": "BOTTOM",
#                 "participantId": 8,
#                 "csDiffPerMinDeltas": {
#                     "0-10": -1.2,
#                     "10-20": -0.4000000000000006
#                 },
#                 "goldPerMinDeltas": {
#                     "0-10": 240,
#                     "10-20": 319.2
#                 },
#                 "xpDiffPerMinDeltas": {
#                     "0-10": -92.70000000000002,
#                     "10-20": -0.6999999999999886
#                 },
#                 "creepsPerMinDeltas": {
#                     "0-10": 6.5,
#                     "10-20": 6
#                 },
#                 "xpPerMinDeltas": {
#                     "0-10": 273.7,
#                     "10-20": 427.1
#                 },
#                 "role": "DUO_CARRY",
#                 "damageTakenDiffPerMinDeltas": {
#                     "0-10": 47.80000000000002,
#                     "10-20": -119.80000000000007
#                 },
#                 "damageTakenPerMinDeltas": {
#                     "0-10": 302.4,
#                     "10-20": 522.7
#                 }
#             },
#             "spell2Id": 4,
#             "teamId": 200,
#             "stats": {
#                 "neutralMinionsKilledTeamJungle": 0,
#                 "visionScore": 16,
#                 "magicDamageDealtToChampions": 1521,
#                 "largestMultiKill": 0,
#                 "totalTimeCrowdControlDealt": 612,
#                 "longestTimeSpentLiving": 392,
#                 "perk1Var1": 121,
#                 "perk1Var3": 0,
#                 "perk1Var2": 160,
#                 "tripleKills": 0,
#                 "perk5": 8410,
#                 "perk4": 8345,
#                 "playerScore9": 0,
#                 "playerScore8": 0,
#                 "kills": 0,
#                 "playerScore1": 0,
#                 "playerScore0": 0,
#                 "playerScore3": 0,
#                 "playerScore2": 0,
#                 "playerScore5": 0,
#                 "playerScore4": 0,
#                 "playerScore7": 0,
#                 "playerScore6": 0,
#                 "perk5Var1": 107,
#                 "perk5Var3": 0,
#                 "perk5Var2": 0,
#                 "totalScoreRank": 0,
#                 "neutralMinionsKilled": 0,
#                 "statPerk1": 5008,
#                 "statPerk0": 5005,
#                 "damageDealtToTurrets": 764,
#                 "physicalDamageDealtToChampions": 10836,
#                 "damageDealtToObjectives": 866,
#                 "perk2Var2": 0,
#                 "perk2Var3": 0,
#                 "totalUnitsHealed": 4,
#                 "perk2Var1": 20,
#                 "perk4Var1": 3,
#                 "totalDamageTaken": 19480,
#                 "perk4Var3": 0,
#                 "wardsKilled": 1,
#                 "largestCriticalStrike": 193,
#                 "largestKillingSpree": 0,
#                 "quadraKills": 0,
#                 "magicDamageDealt": 1521,
#                 "firstBloodAssist": false,
#                 "item2": 2055,
#                 "item3": 3006,
#                 "item0": 1055,
#                 "item1": 3153,
#                 "item6": 3363,
#                 "item4": 3085,
#                 "item5": 0,
#                 "perk1": 9111,
#                 "perk0": 8008,
#                 "perk3": 8014,
#                 "perk2": 9104,
#                 "perk3Var3": 0,
#                 "perk3Var2": 0,
#                 "perk3Var1": 265,
#                 "damageSelfMitigated": 7659,
#                 "magicalDamageTaken": 6634,
#                 "perk0Var2": 40,
#                 "firstInhibitorKill": false,
#                 "trueDamageTaken": 1281,
#                 "assists": 8,
#                 "perk4Var2": 0,
#                 "goldSpent": 7775,
#                 "trueDamageDealt": 6525,
#                 "participantId": 8,
#                 "physicalDamageDealt": 81935,
#                 "sightWardsBoughtInGame": 0,
#                 "totalDamageDealtToChampions": 12358,
#                 "physicalDamageTaken": 11564,
#                 "totalPlayerScore": 0,
#                 "win": false,
#                 "objectivePlayerScore": 0,
#                 "totalDamageDealt": 89982,
#                 "neutralMinionsKilledEnemyJungle": 0,
#                 "deaths": 11,
#                 "wardsPlaced": 9,
#                 "perkPrimaryStyle": 8000,
#                 "perkSubStyle": 8300,
#                 "turretKills": 0,
#                 "firstBloodKill": false,
#                 "trueDamageDealtToChampions": 0,
#                 "goldEarned": 8434,
#                 "killingSprees": 0,
#                 "unrealKills": 0,
#                 "firstTowerAssist": false,
#                 "firstTowerKill": false,
#                 "champLevel": 13,
#                 "doubleKills": 0,
#                 "inhibitorKills": 0,
#                 "firstInhibitorAssist": false,
#                 "perk0Var1": 1,
#                 "combatPlayerScore": 0,
#                 "perk0Var3": 0,
#                 "visionWardsBoughtInGame": 3,
#                 "pentaKills": 0,
#                 "totalHeal": 2252,
#                 "totalMinionsKilled": 160,
#                 "timeCCingOthers": 35,
#                 "statPerk2": 5002
#             },
#             "championId": 22
#         },
#         {
#             "spell1Id": 14,
#             "participantId": 9,
#             "timeline": {
#                 "lane": "MIDDLE",
#                 "participantId": 9,
#                 "csDiffPerMinDeltas": {
#                     "0-10": -0.2999999999999998,
#                     "10-20": 4.800000000000001
#                 },
#                 "goldPerMinDeltas": {
#                     "0-10": 271.5,
#                     "10-20": 564.3
#                 },
#                 "xpDiffPerMinDeltas": {
#                     "0-10": 34.099999999999994,
#                     "10-20": 255.8
#                 },
#                 "creepsPerMinDeltas": {
#                     "0-10": 6.9,
#                     "10-20": 8.9
#                 },
#                 "xpPerMinDeltas": {
#                     "0-10": 462.4,
#                     "10-20": 690.9
#                 },
#                 "role": "SOLO",
#                 "damageTakenDiffPerMinDeltas": {
#                     "0-10": 77.80000000000001,
#                     "10-20": -172.4
#                 },
#                 "damageTakenPerMinDeltas": {
#                     "0-10": 314.7,
#                     "10-20": 545.3
#                 }
#             },
#             "spell2Id": 4,
#             "teamId": 200,
#             "stats": {
#                 "neutralMinionsKilledTeamJungle": 8,
#                 "visionScore": 23,
#                 "magicDamageDealtToChampions": 17325,
#                 "largestMultiKill": 2,
#                 "totalTimeCrowdControlDealt": 202,
#                 "longestTimeSpentLiving": 1440,
#                 "perk1Var1": 704,
#                 "perk1Var3": 0,
#                 "perk1Var2": 0,
#                 "tripleKills": 0,
#                 "perk5": 9105,
#                 "perk4": 8009,
#                 "playerScore9": 0,
#                 "playerScore8": 0,
#                 "kills": 9,
#                 "playerScore1": 0,
#                 "playerScore0": 0,
#                 "playerScore3": 0,
#                 "playerScore2": 0,
#                 "playerScore5": 0,
#                 "playerScore4": 0,
#                 "playerScore7": 0,
#                 "playerScore6": 0,
#                 "perk5Var1": 16,
#                 "perk5Var3": 0,
#                 "perk5Var2": 0,
#                 "totalScoreRank": 0,
#                 "neutralMinionsKilled": 8,
#                 "statPerk1": 5008,
#                 "statPerk0": 5005,
#                 "damageDealtToTurrets": 0,
#                 "physicalDamageDealtToChampions": 4222,
#                 "damageDealtToObjectives": 0,
#                 "perk2Var2": 0,
#                 "perk2Var3": 0,
#                 "totalUnitsHealed": 1,
#                 "perk2Var1": 30,
#                 "perk4Var1": 2685,
#                 "totalDamageTaken": 19835,
#                 "perk4Var3": 0,
#                 "wardsKilled": 5,
#                 "largestCriticalStrike": 0,
#                 "largestKillingSpree": 7,
#                 "quadraKills": 0,
#                 "magicDamageDealt": 107043,
#                 "firstBloodAssist": false,
#                 "item2": 1026,
#                 "item3": 1056,
#                 "item0": 3089,
#                 "item1": 3157,
#                 "item6": 3340,
#                 "item4": 3158,
#                 "item5": 3100,
#                 "perk1": 8143,
#                 "perk0": 8112,
#                 "perk3": 8135,
#                 "perk2": 8138,
#                 "perk3Var3": 0,
#                 "perk3Var2": 5,
#                 "perk3Var1": 2878,
#                 "damageSelfMitigated": 12618,
#                 "magicalDamageTaken": 6972,
#                 "perk0Var2": 0,
#                 "firstInhibitorKill": false,
#                 "trueDamageTaken": 800,
#                 "assists": 6,
#                 "perk4Var2": 500,
#                 "goldSpent": 13985,
#                 "trueDamageDealt": 6559,
#                 "participantId": 9,
#                 "physicalDamageDealt": 26983,
#                 "sightWardsBoughtInGame": 0,
#                 "totalDamageDealtToChampions": 22664,
#                 "physicalDamageTaken": 12063,
#                 "totalPlayerScore": 0,
#                 "win": false,
#                 "objectivePlayerScore": 0,
#                 "totalDamageDealt": 140585,
#                 "neutralMinionsKilledEnemyJungle": 0,
#                 "deaths": 4,
#                 "wardsPlaced": 10,
#                 "perkPrimaryStyle": 8100,
#                 "perkSubStyle": 8000,
#                 "turretKills": 0,
#                 "firstBloodKill": false,
#                 "trueDamageDealtToChampions": 1116,
#                 "goldEarned": 13638,
#                 "killingSprees": 2,
#                 "unrealKills": 0,
#                 "firstTowerAssist": false,
#                 "firstTowerKill": false,
#                 "champLevel": 16,
#                 "doubleKills": 1,
#                 "inhibitorKills": 0,
#                 "firstInhibitorAssist": false,
#                 "perk0Var1": 2016,
#                 "combatPlayerScore": 0,
#                 "perk0Var3": 0,
#                 "visionWardsBoughtInGame": 1,
#                 "pentaKills": 0,
#                 "totalHeal": 3035,
#                 "totalMinionsKilled": 224,
#                 "timeCCingOthers": 13,
#                 "statPerk2": 5002
#             },
#             "championId": 105
#         },
#         {
#             "spell1Id": 11,
#             "participantId": 10,
#             "timeline": {
#                 "lane": "JUNGLE",
#                 "participantId": 10,
#                 "csDiffPerMinDeltas": {
#                     "0-10": -0.30000000000000004,
#                     "10-20": -0.9
#                 },
#                 "goldPerMinDeltas": {
#                     "0-10": 199.60000000000002,
#                     "10-20": 388.29999999999995
#                 },
#                 "xpDiffPerMinDeltas": {
#                     "0-10": -162.70000000000002,
#                     "10-20": -72.89999999999998
#                 },
#                 "creepsPerMinDeltas": {
#                     "0-10": 0.5,
#                     "10-20": 0.1
#                 },
#                 "xpPerMinDeltas": {
#                     "0-10": 263.1,
#                     "10-20": 476.4
#                 },
#                 "role": "NONE",
#                 "damageTakenDiffPerMinDeltas": {
#                     "0-10": 392.9,
#                     "10-20": 351.99999999999994
#                 },
#                 "damageTakenPerMinDeltas": {
#                     "0-10": 831.5,
#                     "10-20": 1238.3
#                 }
#             },
#             "spell2Id": 4,
#             "teamId": 200,
#             "stats": {
#                 "neutralMinionsKilledTeamJungle": 75,
#                 "visionScore": 26,
#                 "magicDamageDealtToChampions": 10573,
#                 "largestMultiKill": 1,
#                 "totalTimeCrowdControlDealt": 220,
#                 "longestTimeSpentLiving": 515,
#                 "perk1Var1": 589,
#                 "perk1Var3": 0,
#                 "perk1Var2": 220,
#                 "tripleKills": 0,
#                 "perk5": 8138,
#                 "perk4": 8135,
#                 "playerScore9": 0,
#                 "playerScore8": 0,
#                 "kills": 2,
#                 "playerScore1": 0,
#                 "playerScore0": 0,
#                 "playerScore3": 0,
#                 "playerScore2": 0,
#                 "playerScore5": 0,
#                 "playerScore4": 0,
#                 "playerScore7": 0,
#                 "playerScore6": 0,
#                 "perk5Var1": 30,
#                 "perk5Var3": 0,
#                 "perk5Var2": 0,
#                 "totalScoreRank": 0,
#                 "neutralMinionsKilled": 89,
#                 "statPerk1": 5008,
#                 "statPerk0": 5005,
#                 "damageDealtToTurrets": 0,
#                 "physicalDamageDealtToChampions": 450,
#                 "damageDealtToObjectives": 901,
#                 "perk2Var2": 50,
#                 "perk2Var3": 0,
#                 "totalUnitsHealed": 1,
#                 "perk2Var1": 17,
#                 "perk4Var1": 2496,
#                 "totalDamageTaken": 35113,
#                 "perk4Var3": 0,
#                 "wardsKilled": 3,
#                 "largestCriticalStrike": 0,
#                 "largestKillingSpree": 0,
#                 "quadraKills": 0,
#                 "magicDamageDealt": 77185,
#                 "firstBloodAssist": false,
#                 "item2": 3157,
#                 "item3": 3111,
#                 "item0": 1414,
#                 "item1": 2055,
#                 "item6": 3364,
#                 "item4": 1052,
#                 "item5": 1033,
#                 "perk1": 9111,
#                 "perk0": 8010,
#                 "perk3": 8014,
#                 "perk2": 9105,
#                 "perk3Var3": 0,
#                 "perk3Var2": 0,
#                 "perk3Var1": 181,
#                 "damageSelfMitigated": 23217,
#                 "magicalDamageTaken": 12334,
#                 "perk0Var2": 0,
#                 "firstInhibitorKill": false,
#                 "trueDamageTaken": 1933,
#                 "assists": 9,
#                 "perk4Var2": 5,
#                 "goldSpent": 8285,
#                 "trueDamageDealt": 4356,
#                 "participantId": 10,
#                 "physicalDamageDealt": 16009,
#                 "sightWardsBoughtInGame": 0,
#                 "totalDamageDealtToChampions": 12107,
#                 "physicalDamageTaken": 20845,
#                 "totalPlayerScore": 0,
#                 "win": false,
#                 "objectivePlayerScore": 0,
#                 "totalDamageDealt": 97550,
#                 "neutralMinionsKilledEnemyJungle": 3,
#                 "deaths": 10,
#                 "wardsPlaced": 10,
#                 "perkPrimaryStyle": 8000,
#                 "perkSubStyle": 8100,
#                 "turretKills": 0,
#                 "firstBloodKill": false,
#                 "trueDamageDealtToChampions": 1084,
#                 "goldEarned": 8572,
#                 "killingSprees": 0,
#                 "unrealKills": 0,
#                 "firstTowerAssist": false,
#                 "firstTowerKill": false,
#                 "champLevel": 13,
#                 "doubleKills": 0,
#                 "inhibitorKills": 0,
#                 "firstInhibitorAssist": false,
#                 "perk0Var1": 631,
#                 "combatPlayerScore": 0,
#                 "perk0Var3": 0,
#                 "visionWardsBoughtInGame": 10,
#                 "pentaKills": 0,
#                 "totalHeal": 13613,
#                 "totalMinionsKilled": 15,
#                 "timeCCingOthers": 14,
#                 "statPerk2": 5002
#             },
#             "championId": 517
#         }
#     ],
#     "gameDuration": 1769,
#     "gameCreation": 1583995753532
# }